local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>t', builtin.find_files, {})
vim.keymap.set('n', '<leader>f', builtin.live_grep, {})
vim.keymap.set('n', '<leader>g', function()
  require("harpoon.ui").toggle_quick_menu()
end, {})
vim.keymap.set('n', '<leader>m', function()
  require("harpoon.mark").add_file()
end, {})
